/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FundsImport } from './routes/funds'
import { Route as IndexImport } from './routes/index'
import { Route as FundsIdImport } from './routes/funds.$id'

// Create/Update Routes

const FundsRoute = FundsImport.update({
  path: '/funds',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/funds.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FundsIdRoute = FundsIdImport.update({
  path: '/$id',
  getParentRoute: () => FundsRoute,
} as any).lazy(() => import('./routes/funds.$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/funds': {
      preLoaderRoute: typeof FundsImport
      parentRoute: typeof rootRoute
    }
    '/funds/$id': {
      preLoaderRoute: typeof FundsIdImport
      parentRoute: typeof FundsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  FundsRoute.addChildren([FundsIdRoute]),
])

/* prettier-ignore-end */
